// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	domain "todo-app/domain"
	client "todo-app/pkg/client"

	mock "github.com/stretchr/testify/mock"
)

// IUserRepo is an autogenerated mock type for the IUserRepo type
type IUserRepo struct {
	mock.Mock
}

// Delete provides a mock function with given fields: filter
func (_m *IUserRepo) Delete(filter map[string]interface{}) error {
	ret := _m.Called(filter)

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}) error); ok {
		r0 = rf(filter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: filter
func (_m *IUserRepo) Get(filter map[string]interface{}) (*domain.User, error) {
	ret := _m.Called(filter)

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}) (*domain.User, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(map[string]interface{}) *domain.User); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(map[string]interface{}) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: filter, paging
func (_m *IUserRepo) GetAll(filter map[string]interface{}, paging *client.Paging) ([]domain.User, error) {
	ret := _m.Called(filter, paging)

	var r0 []domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}, *client.Paging) ([]domain.User, error)); ok {
		return rf(filter, paging)
	}
	if rf, ok := ret.Get(0).(func(map[string]interface{}, *client.Paging) []domain.User); ok {
		r0 = rf(filter, paging)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(map[string]interface{}, *client.Paging) error); ok {
		r1 = rf(filter, paging)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: _a0
func (_m *IUserRepo) Save(_a0 *domain.UserCreate) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.UserCreate) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: filter, _a1
func (_m *IUserRepo) Update(filter map[string]interface{}, _a1 *domain.UserUpdate) error {
	ret := _m.Called(filter, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}, *domain.UserUpdate) error); ok {
		r0 = rf(filter, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIUserRepo creates a new instance of IUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUserRepo {
	mock := &IUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
